server:
  port: ${SPRING_APPLICATION_PORT:8072}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:newspace-gateway}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Eureka에서 서비스 목록 자동 탐색
          lower-case-service-id: true
      routes:
        - id: "newspace-user-service-${USER_SERVICE_STATUS:blue}"
          uri: "lb://newspace-user-service-${USER_SERVICE_STATUS:blue}"  # Eureka에서 유저서비스 서비스 찾기
          predicates:
            - Path=/api/**
        - id: "newspace-notice-service-${NOTICE_SERVICE_STATUS:blue}"
          uri: "lb://newspace-notice-service-${NOTICE_SERVICE_STATUS:blue}"  # Eureka에서 알림서비스 서비스 찾기
          predicates:
            - Path=/api/**
        - id: "newspace-news-service-${NEWS_SERVICE_STATUS:blue}"
          uri: "lb://newspace-news-service-${NEWS_SERVICE_STATUS:blue}"  # Eureka에서  뉴스서비스 찾기
          predicates:
            - Path=/api/**

eureka:
  instance:
    hostname: newspace-gateway
    preferIpAddress: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://newspace-eureka:8070/eureka/}