server:
  port: ${SPRING_APPLICATION_PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:newspace-user-service}

  token:
    access-token-expiration-time: 900000
    refresh-token-expiration-time: 1209600000
    secret: ${SECRET_TOKEN:token}

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 30MB
      max-file-size: 10MB
      location: /newspace/uploads

  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    url: ${DB_URL:jdbc:mysql://localhost:3306/mydb}
    driver-class-name: org.mariadb.jdbc.Driver

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    preferIpAddress: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    hostname: newspace-user-service
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://newspace-eureka:8070/eureka/}